.PHONY: curve-builder, polardb-builder

curve-builder:
	docker build --target curve-builder --tag opencurvedocker/curve-build:latest-centos7 $(PWD)
polardb-builder:
	docker build --target polardb-builder --tag opencurvedocker/polardb-build:latest-centos7 $(PWD)